// Add new posts here — each one just needs a unique slug, a title/date/excerpt
// for the list page, and a body (array of paragraphs) for the detail page.
export const BLOG_POSTS = [
  {
    slug: 'how-elpis-began',
    title: 'How Elpis Began',
    date: 'July 22, 2026',
    excerpt: "Why we built Elpis: not another standalone tool, but one connected place for everything that happens between appointments — where cancer care actually gets hard.",
    body: [
      "Elpis began with a simple question: Why is the cancer journey still so overwhelming, even with today's incredible advances in medicine? Every year, breakthroughs in cancer research continue to improve diagnosis, treatment, and survival rates. Yet for millions of patients and their families, the experience of navigating cancer remains deeply complex and emotionally exhausting. A diagnosis doesn't just introduce medical challenges—it brings uncertainty, fear, endless appointments, difficult decisions, unfamiliar terminology, insurance paperwork, medication schedules, and the responsibility of coordinating care across multiple providers. For many, it can feel like managing a full-time job while fighting for their health.",
      "As we explored the realities of cancer care, one thing became increasingly clear: the problem wasn't a lack of medical expertise. Healthcare professionals dedicate their lives to caring for patients, and hospitals have access to remarkable technology and treatments. The challenge lies in everything that happens between appointments—the moments when patients return home with unanswered questions, caregivers struggle to coordinate daily responsibilities, or families simply don't know what comes next. These gaps often leave patients feeling isolated and overwhelmed during one of the most vulnerable periods of their lives.",
      "We also realized that most existing digital tools address only a small part of the journey. One application helps manage appointments, another stores medical documents, another offers telehealth services, while yet another provides educational resources. Patients and caregivers are left switching between disconnected systems, trying to piece together their own support network. Instead of simplifying cancer care, technology often adds another layer of complexity.",
      "That realization became the foundation of Elpis.",
      "Rather than building another standalone feature or another AI chatbot, we envisioned a platform that could bring every part of the cancer journey into one connected experience. We wanted a place where patients could understand their diagnosis in clear language, keep track of medications and appointments, securely communicate with their care team, organize important medical documents, monitor symptoms, involve caregivers, and connect with others who truly understand what they're going through. More importantly, we wanted technology to quietly work in the background—anticipating needs, reducing confusion, and helping patients focus less on logistics and more on healing.",
      "The name Elpis comes from the ancient Greek word for hope. In Greek mythology, Elpis represents the hope that remains even in the face of hardship. We chose this name because hope is more than optimism; it's what helps people continue moving forward through uncertainty. Hope is found in a reassuring conversation with a nurse, in a caregiver's support, in a survivor's story, in ringing the bell after treatment, and in every small victory along the journey.",
      "At its core, Elpis is built on a simple belief: no one should ever feel lost during their cancer journey. Our mission is not to replace the compassion of doctors, nurses, or caregivers, but to strengthen the connections between them. By bringing patients, caregivers, and healthcare teams together in one coordinated platform, we hope to reduce the burden of navigating care and give people something that is often just as important as treatment itself—a sense of clarity, connection, and hope.",
      "This is how Elpis began. And while our technology will continue to evolve, our mission will always remain the same: to ensure that every patient, every caregiver, and every family feels supported through every step of the cancer journey.",
    ],
  },
  {
    slug: 'finding-the-right-partner',
    title: 'Finding the Right Partner',
    date: 'July 22, 2026',
    excerpt: "Before there was Elpis, there was a DevDays teammate, a summer of side conversations, and one question that changed everything: what would we build if a hospital asked us to solve this tomorrow?",
    body: [
      'Every great project begins with an idea, but turning that idea into something real almost always requires the right people. For Elpis, that journey started long before we wrote a single line of code.',
      'I first met Prabhakar Shrestha during the 2025 Nexus Louisiana DevDays competition, where we worked together on StepSight AI, a project focused on supporting ACL injury recovery. Our goal was to explore how artificial intelligence could help patients better understand their rehabilitation process by providing insights and guidance throughout recovery. Like many student teams, we spent countless hours brainstorming ideas, solving technical challenges, and preparing our final presentation. More importantly, we learned how each of us approached problems, communicated under pressure, and worked through setbacks as a team.',
      "Although DevDays eventually came to an end, our collaboration didn't. We stayed in touch, occasionally discussing new technologies, sharing interesting ideas, and talking about projects we wanted to build outside of class. Neither of us wanted our learning to stop when the semester ended. We both shared the belief that the best way to improve as developers wasn't just by completing assignments—it was by building real products that solved meaningful problems.",
      "During the summer, what started as a casual conversation quickly became something much bigger. We were talking about how we wanted to spend our break working on projects instead of letting the months pass by. There wasn't a specific goal at first—we simply wanted to build something together. As we exchanged ideas, we realized we shared the same mindset. We weren't interested in creating another portfolio project that would sit on GitHub after a few weeks. We wanted to build software that people could genuinely imagine using in the real world.",
      'Around that same time, Nexus Louisiana announced the 2026 DevDays Cancer Care & Prevention Challenge in partnership with Ochsner Health. The challenge immediately caught our attention. Cancer is something that touches nearly every family in one way or another, and the opportunity to create technology that could improve the lives of patients and caregivers felt deeply meaningful. Instead of thinking about how we could simply compete, we started asking ourselves a different question:',
      '"What would we build if a hospital asked us to solve this problem tomorrow?"',
      'That question changed everything.',
      'Rather than approaching the competition as another hackathon, we decided to approach it like the beginning of a startup. We spent our time researching the cancer care journey, studying where patients experience the greatest challenges, understanding the perspectives of caregivers and healthcare providers, and thinking about how technology could reduce—not add to—the complexity of cancer care.',
      'Those conversations eventually led to the idea that became Elpis.',
      "What began as two friends discussing summer projects evolved into a shared mission: to create a platform that could make the cancer journey feel less overwhelming, more connected, and more hopeful. Looking back, it's hard to imagine Elpis existing without those spontaneous conversations. Sometimes the best partnerships don't begin with a business plan or a grand vision—they begin with two people who simply enjoy building together and believe that technology can make a meaningful difference.",
      "Working together again after StepSight AI also gave us a unique advantage. We already understood each other's strengths, trusted each other's decisions, and knew how to collaborate effectively under the time constraints of a competition. That foundation allowed us to spend less time figuring out how to work together and more time focusing on building something we were genuinely proud of.",
      'In many ways, Elpis wasn\'t just the next project we built—it was the natural continuation of a partnership that began a year earlier, united by a shared curiosity, a passion for solving real-world problems, and the belief that great technology should always put people first.',
    ],
  },
];
